In [1]:
#question 1
import numpy as np

def matrix_generator(mat,n,increasing=False):
    if not increasing:
        final_matrix = np.array([x**(n-1-i) for x in mat for i in range(n)]).reshape(mat.size,n)
    else:
        final_matrix = np.array([x**i for x in mat for i in range(n)]).reshape(mat.size,n)
        
    return final_matrix

matrix1 = np.array([1,2,3,4,5])
degree = 3

print(matrix_generator(matrix1,degree,True))
print(matrix_generator(matrix1,degree,False))


[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


In [9]:
#question 2
def average(a,n):
    x = np.cumsum(a,dtype=float)
    x[n:] = x[n:] - x[:-n]
    return x[n-1:] / n

a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n=3
print(average(a, n))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
